---
# https://github.com/marketplace/actions/setup-cloudflared
#
name: Apply - Terraform via Cloudflared
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v3
      - uses: oHTGo/setup-cloudflare-warp-action@master
        with:
          organization: makeitworkcloud
          auth-client-id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          auth-client-secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

      - name: Connectivity test
        run: |
          curl -k https://api.makeitwork.cloud:6443