---
name: Apply - Terraform via ARC
on:
  push:
    branches:
      - main

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  deploy:
    runs-on: arc-dind
    container: image-registry.openshift-image-registry.svc:5000/arc-runners/terraform-runner:latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_username: ${{ secrets.OPENSHIFT_USERNAME }}
          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
          insecure_skip_tls_verify: true

      - name: Terraform apply
        run: make apply || ( cat /github/home/.cache/pre-commit/pre-commit.log && exit 1 )
