---
# https://github.com/marketplace/actions/setup-cloudflared
#
name: Apply - Terraform via Cloudflared
on:
  push:
    branches:
      - main

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: nhedger/setup-sops@v2
      - uses: hashicorp/setup-terraform@v3
      - uses: redhat-actions/oc-installer@v1
      - uses: oHTGo/setup-cloudflare-warp-action@master
        with:
          organization: makeitworkcloud
          auth-client-id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          auth-client-secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

      - uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_username: ${{ secrets.OPENSHIFT_USERNAME }}
          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
          insecure_skip_tls_verify: true

      - run: make init
        shell: /bin/bash
      - run: make plan
        shell: /bin/bash